allowBuilds:
  esbuild: set this to true or false
minimumReleaseAgeExclude:
  - '@sanity/diff@6.5.0'
  - '@sanity/mutator@6.5.0'
  - '@sanity/schema@6.5.0'
  - '@sanity/types@6.5.0'
  - '@sanity/util@6.5.0'
  - '@sanity/vision@6.5.0'
  - sanity@6.5.0
